
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alizeidillazyuksel
 */
public class Piano extends javax.swing.JFrame {

    /**
     * Creates new form Piano
     */
    public Piano() {
        initComponents();
        
        getContentPane().setBackground(new java.awt.Color(255, 192, 203)); // Pink
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("STIX Two Text", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("My Mini Piano");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 780, 100));

        jButton1.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        jButton1.setText("D");
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 60, 280));

        jButton2.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        jButton2.setText("E");
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 60, 280));

        jButton3.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        jButton3.setText("F");
        jButton3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 60, 280));

        jButton4.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        jButton4.setText("G");
        jButton4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 60, 280));

        jButton5.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        jButton5.setText("C");
        jButton5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 60, 280));

        jButton6.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        jButton6.setText("B");
        jButton6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 60, 280));

        jButton7.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        jButton7.setText("C1");
        jButton7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 60, 280));

        jButton8.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        jButton8.setText("D1");
        jButton8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 60, 280));

        jButton9.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        jButton9.setText("F1");
        jButton9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 60, 280));

        jButton10.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        jButton10.setText("A");
        jButton10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 60, 280));

        jButton11.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        jButton11.setText("E1");
        jButton11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 60, 280));

        jButton12.setBackground(new java.awt.Color(153, 153, 153));
        jButton12.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        jButton12.setText("D#");
        jButton12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 70, 240));

        jButton13.setBackground(new java.awt.Color(153, 153, 153));
        jButton13.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        jButton13.setText("C#");
        jButton13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 70, 240));

        jButton14.setBackground(new java.awt.Color(153, 153, 153));
        jButton14.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        jButton14.setText("Bb");
        jButton14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 70, 240));

        jButton15.setBackground(new java.awt.Color(153, 153, 153));
        jButton15.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        jButton15.setText("F#");
        jButton15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 70, 240));

        jButton16.setBackground(new java.awt.Color(153, 153, 153));
        jButton16.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        jButton16.setText("D#1");
        jButton16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 70, 240));

        jButton17.setBackground(new java.awt.Color(153, 153, 153));
        jButton17.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        jButton17.setText("C#1");
        jButton17.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 70, 240));

        jButton18.setBackground(new java.awt.Color(153, 153, 153));
        jButton18.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        jButton18.setText("G#");
        jButton18.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 70, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                
        try{
        String path = "/Users/alizeidillazyuksel/Downloads/piano/E.wav";
        AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
        Clip player = AudioSystem.getClip();
        player.open(audio);
        player.start();
                
        }catch(Exception e){
            
        }  
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                
        try{
        String path = "/Users/alizeidillazyuksel/Downloads/piano/G.wav";
        AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
        Clip player = AudioSystem.getClip();
        player.open(audio);
        player.start();
                
        }catch(Exception e){
            
        }  
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
                
        try{
        String path = "/Users/alizeidillazyuksel/Downloads/piano/C1.wav";
        AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
        Clip player = AudioSystem.getClip();
        player.open(audio);
        player.start();
                
        }catch(Exception e){
            
        }  
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
                
        try{
        String path = "/Users/alizeidillazyuksel/Downloads/piano/F1.wav";
        AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
        Clip player = AudioSystem.getClip();
        player.open(audio);
        player.start();
                
        }catch(Exception e){
            
        }  
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
                
        try{
        String path = "/Users/alizeidillazyuksel/Downloads/piano/E1.wav";
        AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
        Clip player = AudioSystem.getClip();
        player.open(audio);
        player.start();
                
        }catch(Exception e){
            
        }  
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                
        try{
        String path = "/Users/alizeidillazyuksel/Downloads/piano/F.wav";
        AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
        Clip player = AudioSystem.getClip();
        player.open(audio);
        player.start();
                
        }catch(Exception e){
            
        }  
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
                
        try{
        String path = "/Users/alizeidillazyuksel/Downloads/piano/B.wav";
        AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
        Clip player = AudioSystem.getClip();
        player.open(audio);
        player.start();
                
        }catch(Exception e){
            
        }  
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
                
        try{
        String path = "/Users/alizeidillazyuksel/Downloads/piano/C_s1.wav";
        AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
        Clip player = AudioSystem.getClip();
        player.open(audio);
        player.start();
                
        }catch(Exception e){
            
        }  
        
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
                       
        try{
        String path = "/Users/alizeidillazyuksel/Downloads/piano/D_s1.wav";
        AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
        Clip player = AudioSystem.getClip();
        player.open(audio);
        player.start();
                
        }catch(Exception e){
            
        }  
            
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        
        try{
        String path = "/Users/alizeidillazyuksel/Downloads/piano/F_s.wav";
        AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
        Clip player = AudioSystem.getClip();
        player.open(audio);
        player.start();
                
        }catch(Exception e){
            
        }  
        
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        try{
        String path = "/Users/alizeidillazyuksel/Downloads/piano/C.wav";
        AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
        Clip player = AudioSystem.getClip();
        player.open(audio);
        player.start();
                
        }catch(Exception e){
            
        }        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                
        try{
        String path = "/Users/alizeidillazyuksel/Downloads/piano/D.wav";
        AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
        Clip player = AudioSystem.getClip();
        player.open(audio);
        player.start();
                
        }catch(Exception e){
            
        }  
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
                        
        try{
        String path = "/Users/alizeidillazyuksel/Downloads/piano/C_s.wav";
        AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
        Clip player = AudioSystem.getClip();
        player.open(audio);
        player.start();
                
        }catch(Exception e){
            
        }  
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
                                
        try{
        String path = "/Users/alizeidillazyuksel/Downloads/piano/A.wav";
        AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
        Clip player = AudioSystem.getClip();
        player.open(audio);
        player.start();
                
        }catch(Exception e){
            
        }  
       
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
                                
        try{
        String path = "/Users/alizeidillazyuksel/Downloads/piano/D1.wav";
        AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
        Clip player = AudioSystem.getClip();
        player.open(audio);
        player.start();
                
        }catch(Exception e){
            
        }  
       
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
                                
        try{
        String path = "/Users/alizeidillazyuksel/Downloads/piano/D_s.wav";
        AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
        Clip player = AudioSystem.getClip();
        player.open(audio);
        player.start();
                
        }catch(Exception e){
            
        }  
       
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
                                
        try{
        String path = "/Users/alizeidillazyuksel/Downloads/piano/G_s.wav";
        AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
        Clip player = AudioSystem.getClip();
        player.open(audio);
        player.start();
                
        }catch(Exception e){
            
        }  
       
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
                                
        try{
        String path = "/Users/alizeidillazyuksel/Downloads/piano/Bb.wav";
        AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
        Clip player = AudioSystem.getClip();
        player.open(audio);
        player.start();
                
        }catch(Exception e){
            
        }  
       
    }//GEN-LAST:event_jButton14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Piano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
